CREATE TABLE area_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50) NOT NULL,
    location_id BIGINT      NOT NULL,
    CONSTRAINT pk_area_types PRIMARY KEY (id)
);

CREATE TABLE areas
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(50) NOT NULL,
    description    VARCHAR(100),
    type           VARCHAR(255),
    phone          VARCHAR(255),
    address1       VARCHAR(255),
    address2       VARCHAR(255),
    city           VARCHAR(255),
    state          VARCHAR(255),
    zip            VARCHAR(255),
    country        VARCHAR(255),
    status         VARCHAR(255),
    location_id    BIGINT      NOT NULL,
    parent_area_id BIGINT,
    CONSTRAINT pk_areas PRIMARY KEY (id)
);

CREATE TABLE location
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    phone       VARCHAR(255),
    address1    VARCHAR(255),
    address2    VARCHAR(255),
    city        VARCHAR(255),
    state       VARCHAR(255),
    zip         VARCHAR(255),
    country     VARCHAR(255),
    CONSTRAINT pk_location PRIMARY KEY (id)
);

ALTER TABLE area_types
    ADD CONSTRAINT uc_a6a69b292919e9e32759e5c21 UNIQUE (name, location_id);